### ISSUE TITLE
'SEARCH_PATH' is not defined

### ISSUE THREAD

**Issue by EZSyncAI** [bri-bri/yosemite-camping#4]
Great work thank you I think I almost get it running except this error below.can someone help?

Traceback (most recent call last):
  File "campsites.py", line 133, in <module>
    sites = findCampSites(arg_dict)
  File "campsites.py", line 67, in findCampSites
    content_raw = sendRequest(payload)
  File "campsites.py", line 118, in sendRequest
    "ERROR, %d code received from %s".format(resp.status_code, BASE_URL + SEARCH_PATH))
NameError: name 'SEARCH_PATH' is not defined

**Comment by 000011111111** [comment]
Are you available to get some of the basic test scripts working with the
automation software?

On Sep 29, 2018 1:14 PM, "Dan" <notifications@github.com> wrote:

Great work thank you I think I almost get it running except this error
below.can someone help?

Traceback (most recent call last):
File "campsites.py", line 133, in
sites = findCampSites(arg_dict)
File "campsites.py", line 67, in findCampSites
content_raw = sendRequest(payload)
File "campsites.py", line 118, in sendRequest
"ERROR, %d code received from %s".format(resp.status_code, BASE_URL +
SEARCH_PATH))
NameError: name 'SEARCH_PATH' is not defined

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/bri-bri/yosemite-camping/issues/4>, or mute the thread

**Comment by stebrown** [comment]
'SEARCH_PATH' is not defined in the campsites.py file, which is causing the error. In addition to this, it seems like there's an issue with how "format" is being used in the exception. To clean this up and make the exception return properly, your line 118 could be changed to something like:
`            raise Exception("failedRequest","ERROR, %d code received from %s" % (resp.status_code, BASE_URL + UNIF_SEARCH))`

However, the exception reporting isn't the biggest problem here. The problem is that the exception is being triggered at all. If you make the change noted above, you'll see that `resp.status_code` is giving a 403 code instead of the desired 200. I believe this means that access is being forbidden by the server, maybe because the session spoofing that the script is set up to do is no longer working properly?

Getting the whole thing back up and working is a little beyond my knowledge, but if anybody has managed to do it, more help on this would be very much appreciated.

**Comment by professorjedi** [comment]
Does anyone have this working... kinda new to python so trying diff things

**Comment by hajjat** [comment]
<div class="js-discussion js-socket-channel ml-0 pl-0 ml-md-6 pl-md-3" data-channel="eyJjIjoibWFya2VkLWFzLXJlYWQ6NzgwNjcxIiwidCI6MTYyMjI2Njk3Mn0=--407c2c575b604a05623a41b15ffa95a78545cf911607c699b867e55741a1493d" data-channel-target="MDU6SXNzdWU4MzIwNTE3Njk=" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 16px !important; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box;"><div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg1MDc3NDM1Ng==" style="box-sizing: border-box;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg1MDc3NDM1Ng==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg1MDc3NDM1Ng==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-850774356" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container editable-comment js-comment timeline-comment--caret reorderable-task-lists current-user" data-body-version="5c1884272c91f85536d82d5087c26c724c923ea5f94e71f4d53f5d7ce43bfe31" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border-color: var(--color-box-border-info); border-top-style: ; border-top-width: ; border-right-style: ; border-right-width: ; border-bottom-style: ; border-bottom-width: ; border-left-style: ; border-left-width: ; border-image-source: ; border-image-slice: ; border-image-width: ; border-image-outset: ; border-image-repeat: ; border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists sortable="" style="box-sizing: border-box;">Not working for me either. Even if&nbsp;SEARCH_PATH&nbsp;is defined, you'll hit another issue. I believe the URL&nbsp;https://www.recreation.gov/unifSearch.do&nbsp;the script uses is&nbsp;not&nbsp;valid anymore. Seems the website got refactored.</task-lists></div><form class="js-comment-update" id="issuecomment-850774356-edit-form" action="https://github.com/bri-bri/yosemite-camping/issue_comments/850774356" accept-charset="UTF-8" method="post" style="box-sizing: border-box;"></form></div></div></div></div><div style="box-sizing: border-box;"><div class="js-timeline-marker js-socket-channel js-updatable-content" id="partial-timeline" data-channel="eyJjIjoiaXNzdWU6ODMyMDUxNzY5IiwidCI6MTYyMjI2NzI3NH0=--c5f0a9a83f7407e7ee42d4effb1024c84081c6865a035c129cde810f61c926cf" data-url="/_render_node/MDU6SXNzdWU4MzIwNTE3Njk=/issues/unread_timeline?variables%5BdeferCommitBadges%5D=false&amp;variables%5BdeferStatusCheckRollups%5D=false&amp;variables%5BdeferredCommentActions%5D=true&amp;variables%5BhasFocusedReviewComment%5D=false&amp;variables%5BhasFocusedReviewThread%5D=false&amp;variables%5BtimelinePageSize%5D=30&amp;variables%5BtimelineSince%5D=2021-05-29T05%3A35%3A34Z" data-last-modified="Sat, 29 May 2021 05:35:34 GMT" data-gid="MDU6SXNzdWU4MzIwNTE3Njk=" style="box-sizing: border-box;"></div></div></div></div><span id="issue-comment-box" style="box-sizing: border-box; color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></span><span style="color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><div class="discussion-timeline-actions" style="box-sizing: border-box; background-color: var(--color-bg-canvas); border-top: 2px solid var(--color-border-primary); color: rgb(36, 41, 46); font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="timeline-comment-wrapper timeline-new-comment js-comment-container js-targetable-element  ml-0 pl-0 ml-md-6 pl-md-3" id="issuecomment-new" style="box-sizing: border-box; margin-left: 40px !important; padding-left: 56px; position: relative; margin-top: 16px; margin-bottom: 0px;"><div class=" d-none d-md-block" style="box-sizing: border-box; display: block !important;"><br class="Apple-interchange-newline"></div></div></div>
