### ISSUE TITLE
NameError: global name 'SEARCH_PATH' is not defined

### ISSUE THREAD

**Issue by ghost** [bri-bri/yosemite-camping#6]
$ sudo python campsites.py --start_date 2021-08-05 --end_date 2021-08-09
Traceback (most recent call last):
  File "campsites.py", line 125, in <module>
    sites = findCampSites(arg_dict)
  File "campsites.py", line 65, in findCampSites
    content_raw = sendRequest(payload)
  File "campsites.py", line 110, in sendRequest
    raise Exception("failedRequest","ERROR, %d code received from %s".format(resp.status_code, BASE_URL + SEARCH_PATH))
NameError: global name 'SEARCH_PATH' is not defined

**Comment by hajjat** [comment]
Not working for me either. Even if `SEARCH_PATH` is defined, you'll hit another issue. I believe the URL `https://www.recreation.gov/unifSearch.do` the script uses is **not** valid anymore. Seems the website got refactored.
